---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: num1
      prompt: Enter value for A
      private: false

    - name: num2
      prompt: Enter value for B
      private: false

  tasks:

     - debug:
         msg:
          - "The value of num1 is {{ num1 }} and num2 {{ num2 }}"
          - "num1 is equal to num2: {{ num1==num2 }}"
          - "num1 is not equal to num2: {{ num1 != num2 }}"
          - "num1 greater than num2: {{ num1 < num2 }}"
          - "num1 is less than num2: {{ num1 > num2 }}"
          - "num1 is greater than or equal to num2: {{ num1 >= num2 }}"
          - "num1 is less than or equal to num2: {{ num1 >= num2 }}"
